version: 2

sources:
  - name: company_db
    database: company_db
    schema: company_db
    tables:
      - name: movies
        identifier: movies
      - name: actors
        identifier: actors
      - name: writers
        identifier: writers
